os: 
  - linux

language: php

php: 
  - '7.2'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - cp phpunit.xml.travis phpunit.xml
  - mysql -e "create database skill_matrix_test"
  - php artisan key:generate
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install 10.1.0
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - npm run production

after_success:
  - bash <(curl -s https://codecov.io/bash)
