apiVersion: v1
kind: Service
metadata:
  name: skill-matrix
  labels:
    app: skill-matrix
    app.kubernetes.io/name: skill-matrix
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: 8000-tcp
  selector:
    app: skill-matrix
