apiVersion: v1
kind: Service
metadata:
  labels:
    app: skill-matrix
  name: skill-matrix
  namespace: skill-matrix
spec:
  ports:
  - name: 8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: skill-matrix
  type: ClusterIP
