apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  namespace: skill-matrix
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    deployment: db
  sessionAffinity: None
  type: ClusterIP
